### ISSUE TITLE
Opening linux applications

### ISSUE THREAD

**Issue by KaiH-0** [narren96c/steamos-manjaro#1]
First of all I would like to say this project is amazing and has really helped me. The problem is I can't open external applications such as the normal Retroarch through a shortcut, it runs fine when your on desktop and open steam and run it but as soon as your in SteamOS mode it doesn't open. I have tried other applications and it seems to do the same thing, not quite sure why. If you could help me it would be much appreciated as I also have other people that want to use this repository and apart from that its amazing. Thank you in advance.

**Comment by limbonaut** [comment]
I installed RetroArch from a community repository today, and it launched just fine for me from SteamOS mode. SteamOS mode uses a very simplistic compositor. Some applications like GNOME apps may not run under that compositor.  However, Moonlight runs fine, and RetroArch seems too.

I'm not sure what could be the problem with your RetroArch installation. Did you install it from Manjaro repos? You could try to back up and delete your RetroArch configuration file and see if it starts (~/.config/retroarch/retroarch.cfg).

**Comment by limbonaut** [comment]
You could also install Sakura terminal emulator (if you didn't do it already). You can make a shortcut for it in Steam.

Type this:
`retroarch --verbose > ~/retroarch.log 2>&1`

This will run retroarch and create a log file in your home folder. Should give us more information.

**Comment by KaiH-0** [comment]
That’s the issue, I did that and it does if I run retroarch on desktop mode
but on steamos mode it doesn’t, either way I absolutely love Manjaro but I
had to replace it with Ubuntu with steamos install in the end. U should
definitely do more manjaro projects though as manjaro is superior in my
personal opinion :)

**Comment by limbonaut** [comment]
Thanks for encouragement! I feel Manjaro is a better fit for this as well. It has an easier access to a more recent kernel and Mesa, which positively helps with performance in my experience. Well, if you will decide to give it another go, we may figure out why it doesn't start. I'll close this issue for now.

**Comment by KaiH-0** [comment]
Hi I have decided I would like to try and sort this out as making a steam box with Ubuntu is unbearable it is so much slower for no reason so here I am, I would like to find out why it isn't working, by the way it does it with Sakura terminal too, I can't run it from inside steamos mode which is weird, what version of manjaro gnome did you use?

When I was doing steamos install script on Ubuntu, I did notice it didn't allow desktop apps either until I used steamos tools but sadly that's only for Debian not arch.

**Comment by limbonaut** [comment]
I have an installation from around March. Just the vanilla Manjaro GNOME. It's fully updated, but likely somewhat different from a recent release. Just to be clear, are you using RA from Manjaro repos?

**Comment by KaiH-0** [comment]
Yes I'm using it from the manjaro repo.

**Comment by limbonaut** [comment]
What you can do is run this inside Sakura:
`retroarch --verbose > ~/retroarch.log 2>&1`
 Log file may tell us what's wrong.

**Comment by KaiH-0** [comment]
It doesn't create a log sadly but when in desktop mode it does but doesn't show anything out of the ordinary, but it happens with all desktop applications so I don't think it's just a retroarch issue.

**Comment by limbonaut** [comment]
Most GNOME apps need Mutter to function and it's not present in stream os session. I'll do a quick fresh install and see what's going on.

**Comment by KaiH-0** [comment]
Okay let me know how it goes, thank you for helping! Just to let you know I used the latest version of Manjaro Gnome

**Comment by limbonaut** [comment]
Figured out what seems to be the problem. The modeswitch inhibitor libs prevent desktop apps from running.
For now, you can edit /usr/bin/steamos-session and comment out line like this:
`export LD_PRELOAD=/usr/lib/libmodeswitch...`
This will disable those libs, however, it also will allow games to change display resolution, which is not ideal.

**Comment by KaiH-0** [comment]
Okay I will give this a go tomorrow and let you know, thank you so much for your help! 😁

**Comment by limbonaut** [comment]
Don't edit that file. Just install this:
`pamac install lib32-libxrandr`
Let me know if it helps, so I can add this to installation script!

**Comment by KaiH-0** [comment]
Now the script says target not found steam-manjaro

**Comment by limbonaut** [comment]
I added installing of the lib32-libxrandr to the script. Should be working out-of-the-box now, if you run the updated installation script. I think Manjaro team removed lib32-libxrandr from the installation medium, but it is needed for the inhibition library to function. And it seems it was the reason behind crashing of the desktop apps.

**Comment by KaiH-0** [comment]
Yes it works now, thanks!

**Comment by limbonaut** [comment]
Thanks for reporting, I wouldn't know :)
