### ISSUE TITLE
Proton games forever loading

### ISSUE THREAD

**Issue by KaiH-0** [narren96c/steamos-manjaro#2]
No proton games load when in steamos mode, it just keeps loading but in desktop mode it works.

**Comment by limbonaut** [comment]
Have you tried a different proton version?

**Comment by KaiH-0** [comment]
Different proton version doesn’t work sadly.

**Comment by limbonaut** [comment]
Need more to understand. Could you reboot, try running the game, give it couple minutes? Then switch to terminal (ctrl+alt+F3) and run this:
`journalctl -x --since "5 minutes ago" > system.log`

**Comment by KaiH-0** [comment]
I did that ran the command but it didn’t do anything. It worked but
returned nothing.

**Comment by KaiH-0** [comment]
Do you think that file you told me to edit on the other issue will help?

**Comment by limbonaut** [comment]
No, it's normal. You should have a file called "system.log" in your home folder. Post it here.

**Comment by KaiH-0** [comment]
https://pastebin.pl/view/3bec0dbf Here is the system.log

Might be something to do with this ERROR: ld.so: object '/usr/lib32/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

**Comment by limbonaut** [comment]
That's normal. Steam tries to preload both 32-bit and 64-bit version of inhibitor library for each app it launches and one of them always fails.

**Comment by limbonaut** [comment]
Do you have an issue like that with just this game, or any game using proton?


> Do you think that file you told me to edit on the other issue will help?

I'm not sure. It doesn't hurt to try, though.

**Comment by limbonaut** [comment]
There's also a rare issue with some games running in the background when launched. You can try adding `steam-fg %command%` to launch options in the game properties.

**Comment by KaiH-0** [comment]
Same thing is happening with or without that command and same thing
happened to 3 other games.

**Comment by limbonaut** [comment]
Try disabling the libs in /usr/bin/steamos-session
Put a # in front of this line:
`export LD_PRELOAD=/usr/lib/libmodeswitch_inhibitor.so:/usr/lib32/libmodeswitch_inhibitor.so`

**Comment by KaiH-0** [comment]
Seems to cause other games not to load when doing that.

**Comment by limbonaut** [comment]
I'm not sure what you mean.

**Comment by KaiH-0** [comment]
When commenting out that line it causes every single game, proton or not,
to not load. So no games work.

**Comment by limbonaut** [comment]
What resolution are you setting in your games?

**Comment by KaiH-0** [comment]
1080p

**Comment by limbonaut** [comment]
> When commenting out that line it causes every single game, proton or not, to not load. So no games work.

That's weird... All that line does is prevent games to switch resolution on your display (steam compositor does upscaling instead).

**Comment by KaiH-0** [comment]
Realised python2.7 wasn’t installed but 3 was so gonna see if that makes a
difference as proton uses both so it may be the issue.

**Comment by KaiH-0** [comment]
Didn’t work sadly. Just to make you aware this is using the steam beta as I can't use the normal steam due to library, store etc not loading just black screen, apparently it's a recent update they did that caused that issue.

**Comment by limbonaut** [comment]
This particular line in the log is interesting
`Sep 09 17:39:40 kai-Steambox /usr/lib/gdm-x-session[689]: Warning: The game hasn't rendered a frame from us in over 10 seconds`
It seems like the game launches, but for some reason doesn't render any frames...
And a number of these show up consistently:
`Sep 09 17:39:46 kai-Steambox /usr/lib/gdm-x-session[689]: Not pushing commands this frame due to failed lock`
Definitely doesn't happen on my hardware

**Comment by KaiH-0** [comment]
Hmm that is weird. I still don’t understand why it works in desktop mode
but not steamos if it’s about rendering frames. Maybe xrandr causing issues
or something?

**Comment by limbonaut** [comment]
You could try installing a combination of a different kernel + driver in "Manjaro Settings". 
Also, not sure if you tried already, but maybe worth it - a beta of steam client.

**Comment by KaiH-0** [comment]
Did that it didn't make a difference. Could this be something as it happens with all the proton ones

Failed to load plugin '/home/steam/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0

It does this for other plugins under lib64 folder too

**Comment by limbonaut** [comment]
You can try running a game with PROTON_LOG=1 %command%.
If I understand it correctly, it should create a detailed log in your home folder.

**Comment by KaiH-0** [comment]
I managed to fix the issue by installing steam-compositor-plus, it should
probably be added to the script :) Thank you so much for your help!

**Comment by limbonaut** [comment]
That's interesting... It is actually installed by the script.
`pamac build --no-confirm steamos-compositor-plus`

**Comment by KaiH-0** [comment]
Hmm weird, it could be because it’s a newer version I installed? I did look
at the steamos-session after and it had all changed so maybe in the script
it isn’t getting access to the steamos-session file?

**Comment by limbonaut** [comment]
Did you install it from AUR?

**Comment by KaiH-0** [comment]
Yes, but it kept saying it couldn’t find it so I had to download it and do
it manually from the aur website. One more thing is do you know why some games work on Debian but aren't working on Arch? So weird.

**Comment by limbonaut** [comment]
Oh, I see that last update was yesterday. It is possible, that something changed in the package!

**Comment by limbonaut** [comment]
This is what release says: 
`fix game focus in latest Steam`
Seems like your issue has been fixed 33 hours ago.

**Comment by KaiH-0** [comment]
Yes it could of been that as it seems to allow any game to be run and it
also fixed the issue with the game going really really tiny in the top left
corner which I had on a odd occasion.

**Comment by limbonaut** [comment]
Glad it's been sorted out for you!
