### ISSUE TITLE
Update Request: Holo 3.0 AUR Repos to replace Manjaro Apps? 

### ISSUE THREAD

**Issue by Nulled-Out** [narren96c/steamos-manjaro#4]
Perhaps SteamOS 3 (Holo) Software can be pulled from AUR instead of Manjaro repos? Could be an updated way to get a 'Steamjaro' OS? 🤔 

Could even get kernel upgrades from there too 🤞🏼👀

**Comment by FOSS-Archives** [comment]
Could be useful for users trying to find 3.0 for PC but are too new to Linux & AUR to compile and pull the modules for themselves? @narren96c 🙏🏽
